kind: pipeline
name: syntax-php7.3

steps:
  - name: syntax-php7.3
    image: nextcloudci/php7.3:php7.3-5
    environment:
      APP_NAME: workflow_pdf_converter
      CORE_BRANCH: master
      DB: sqlite
    commands:
      # Pre-setup steps
      - composer install
      - ./vendor/bin/parallel-lint --exclude ./vendor/ .

type: docker

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push
