name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up node
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Set up npm
      run: npm i -g npm@7

    - name: npm install and build
      run: |
        npm ci
        npm run build --if-present
